### ISSUE TITLE
Segmented image (C ++) on the output of caffe?

### ISSUE THREAD

**Issue by montekristo1946** [larsroemheld/OSM-HOT-ConvNet#1]
Good afternoon. Please tell me how to get a segmented image (C ++) on the output of caffe?

**Comment by larsroemheld** [comment]
Please consult the caffe "documentation". For my project, I used this script in my own modification: 
https://github.com/larsroemheld/OSM-HOT-ConvNet/blob/master/test_segmentation_segnet.py

In other words, you first train a model and save the weights (using command line or another option). Then you run caffe in "test" mode (where the corresponding prototxt gives the images to be segmented), postprocess the output (convert labels back to colors), and finally save the image.
